Repository Incarnation-p-lee/rvv-intrinsic-doc, pull requests merged in 2023-08, with the labels that each got.

#24 Fix the problem of incomplete coverage of intrinsics.
  rvv-intrinsic-generator/rvv_intrinsic_gen/generator.py
  rvv-intrinsic-generator/rvv_intrinsic_gen/utils.py
Labels: size/M

#25 Vector Permutation
  rvv-intrinsic-generator/rvv_intrinsic_gen/generator.py
  rvv-intrinsic-generator/rvv_intrinsic_gen/utils.py
Labels: size/S

#26 Miscellaneous Vector Functions
  rvv-intrinsic-generator/rvv_intrinsic_gen/generator.py
  rvv-intrinsic-generator/rvv_intrinsic_gen/utils.py
Labels: size/M

#27 Vector Floating-point Arithmetic-V1
  rvv-intrinsic-generator/rvv_intrinsic_gen/generator.py
  rvv-intrinsic-generator/rvv_intrinsic_gen/utils.py
Labels: size/M

#28 Sync upstream code
  rvv-intrinsic-api.md
  rvv-intrinsic-generator/rvv_intrinsic_gen/generator.py
Labels: size/S

#30 [github workflow] Trigger daily regression action for gnu testcases
  .github/workflows/gnu-gcc-daily-build.yml
Labels: size/M

#31 fix the path of artifacts
  .github/workflows/gnu-gcc-daily-build.yml
Labels: size/XS

#32 modify the trigger time
  .github/workflows/gnu-gcc-daily-build.yml
Labels: size/XS
