Repository Incarnation-p-lee/rvv-intrinsic-doc, pull requests merged in 2023-07, with the labels that each got.

#4 Add arch for the GNU test generation.
  rvv-intrinsic-generator/Makefile
Labels: size/S

#8 Xuli/support gnu atuo test
  rvv-intrinsic-generator/Makefile
  rvv-intrinsic-generator/rvv_intrinsic_gen/enums.py
  rvv-intrinsic-generator/rvv_intrinsic_gen/generator.py
  rvv-intrinsic-generator/rvv_intrinsic_gen/main.py
  rvv-intrinsic-generator/rvv_intrinsic_gen/utils.py
Labels: size/L

#12 add -Wno-psabi
  rvv-intrinsic-generator/rvv_intrinsic_gen/generator.py
Labels: size/S

#6 Add driver scripts
  gnu-auto-generated.exp
  intrinsic-test.sh
Labels: size/L

#16 fix march_mabi
  rvv-intrinsic-generator/rvv_intrinsic_gen/generator.py
Labels: size/XS

#19 Vector Integer Arithmetic
  rvv-intrinsic-generator/rvv_intrinsic_gen/generator.py
  rvv-intrinsic-generator/rvv_intrinsic_gen/utils.py
Labels: size/M

#21 12. Vector Fixed-Point Arithmetic Instructions
  rvv-intrinsic-generator/rvv_intrinsic_gen/generator.py
  rvv-intrinsic-generator/rvv_intrinsic_gen/inst.py
  rvv-intrinsic-generator/rvv_intrinsic_gen/utils.py
Labels: size/M

#23 Deleted code by mistake while resolving conflicts
  rvv-intrinsic-generator/rvv_intrinsic_gen/utils.py
Labels: size/XS
